services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=database'
      - 'MYSQL_PASSWORD=1q2w3e4r'
      - 'MYSQL_ROOT_PASSWORD=1q2w3e4r'
      - 'MYSQL_USER=root'
    ports:
      - '3306'
