spring:
  application:
    name: redis-sample
  output:
    ansi:
      enabled: ALWAYS
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      client-name: redis-sample
      connect-timeout:
      repositories:
        enabled: true
  cache:
    redis:
      key-prefix: sample
      use-key-prefix: true
      cache-null-values: true
      enable-statistics: true
      time-to-live: 1m

logging:
  level:
    root: info